# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixel/themepicker/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixel/themepicker/common


PRODUCT_PACKAGES += \
    PixelThemesStub2022_and_newer \
    PixelWallpapers2024 \
    WallpaperAIPrebuilt_10000342 \
    WallpaperEmojiPrebuilt-v4504 \
    PixelLiveWallpaperPrebuilt-26000013 \
    WallpaperEffect \
    WallpaperPickerGoogleRelease
